[build]
builder = "NIXPACKS"
buildCommand = ["npm run build && php artisan storage:link"]

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
