[build]
builder = "NIXPACKS"
buildCommand = "npm run build && ls -l public && ls -l public/storage && ls -l public/storage/images"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
